### ISSUE TITLE
squashfs extraction

### ISSUE THREAD

**Issue by probonopd** [gokrazy/internal#3]
Looking at  `internal/squashfs/writer.go`  I wonder whether you know of any or are working on any methods to extract squashfs images using Go, to list the contents of squashfs images, and to extract particular files from them.

I am pondering whether to write AppImage tools in Go for which this would come handy.

**Comment by stapelberg** [comment]
Have a look at https://github.com/distr1/distri/blob/master/internal/squashfs/reader.go :)

**Comment by probonopd** [comment]
D'oh, stupid me. Thanks!

**Comment by stapelberg** [comment]
No worries. I’ll close this issue now, but feel free to reach out if you get stuck.

**Comment by probonopd** [comment]
Do you plan to move it out of "internal" eventually? One thing I'd be interested in right away would be reading and writing at an offset, similar to https://patchwork.kernel.org/patch/9544197/.

**Comment by stapelberg** [comment]
I have no plans of moving this out of internal, but feel free to publish a new repository with this code and take it from there :)
